# 🐾 Generated by Bot for server constants 🐾
DEFAULT_EMBED_COLOR = 0xF54927
POKEMEOW_APPLICATION_ID = 664508672713424926
CC_SERVER_ID = 1220718310455250996
KHY_USER_ID = 952071312124313611
BURGER_USER_ID = 682429434720288797
SHELL_SHUCKLE_SERVER_ID = 1490116594884411402

# 💦☁────────────────────────────────────────────💦☁
#       SHELLSHUCKLE_TEXT_CHANNELS
# 💦☁────────────────────────────────────────────💦☁
class SHELLSHUCKLE_TEXT_CHANNELS:
    autospawn = 1491259323526021150

    # 🌊💙🤍───────────── Admin ─────────────💙🤍🌊

    moderator_only = 1490470353099817033
    server_logs = 1490599209940947035
    message_logs = 1490599308012290138
    commands = 1490599712435212368
    todo_list = 1490602637878366208

    # 🌊💙🤍───────────── Market ─────────────💙🤍🌊

    legendmegagmax_feed = 1490880875171283106
    shiny_feed = 1490880740400042196
    golden_feed = 1490880670204170341
    market_snipe = 1490887466255646861
    curs_feed = 1490881002866872390

    # 🌊💙🤍───────────── Uncategorized ─────────────💙🤍🌊

    rules = 1490470353099817030

    # 🌊💙🤍───────────── _Neighborhood ─────────────💙🤍🌊

    clan_ideas = 1490419812042801283
    fries_shrine = 1490430544847306752
    general = 1490495511634116778
    clan_ad = 1490719859733168261
    founders_chat = 1490116595664683180

    # 🌊💙🤍───────────── _Players_Channels ─────────────💙🤍🌊

    notkleptor = 1490118098861293628
    burger = 1490117441945079960
    celia = 1490117592151621692
    pika = 1490117685470691490
    godjinn = 1490117821630255154
    fries = 1490117652230705234
    kleptorlol = 1490117903704522793

    # 🌊💙🤍───────────── Pocketmonster_Street ─────────────💙🤍🌊

    rare_spawns = 1490876341690831118
    battle_unlocks = 1490876557219332146
    waterstate_monitor = 1490888139986833489
    trade_negotiation = 1490428433728147496


# 💦☁────────────────────────────────────────────💦☁
#       SHELLSHUCKLE_VOICE_CHANNELS
# 💦☁────────────────────────────────────────────💦☁
class SHELLSHUCKLE_VOICE_CHANNELS:

    # 🌊💙🤍───────────── Voice_Channels ─────────────💙🤍🌊

    lobby = 1490116595664683183
    gaming = 1490116595664683184


# 💦☁────────────────────────────────────────────💦☁
#       SHELLSHUCKLE_CATEGORIES
# 💦☁────────────────────────────────────────────💦☁
class SHELLSHUCKLE_CATEGORIES:

    ADMIN = 1490598993393352704
    MARKET = 1490875682639843461
    _NEIGHBORHOOD = 1490116595664683179
    _PLAYERS_CHANNELS = 1490117523864158431
    VOICE_CHANNELS = 1490116595664683182
    POCKETMONSTER_STREET = 1490427928134291566


# 💦☁────────────────────────────────────────────💦☁
#       SHELLSHUCKLE_ROLES
# 💦☁────────────────────────────────────────────💦☁
class SHELLSHUCKLE_ROLES:

    _unknown = 1490876248577020086
    pokémeow = 1490117261824884991
    meowhelper = 1490157032890699829
    clan_owner_ = 1490425164779753684
    co_owner = 1490509552079212594
    helper = 1490509049140347082
    shellshuckle_ = 1490424806179471361
    founders_ = 1490176919650701373
    khys_takoyaki_shop = 1490494779790983350
    carl_bot = 1490466598094373110
    muted = 1490468193268011069
    adventurer = 1490471537894101043
    npc = 1490472107287515223
    asia = 1490480975828877453
    north_america = 1490481024470225168
    africa = 1490481052735770675
    south_america = 1490481118015656036
    australia = 1490481218490335363
    antarctica = 1490481351089065985
    europe = 1490481442399064105
    hehim = 1490481736549924914
    sheher = 1490481769378480378
    theythem = 1490481795706392797
    shuckle = 1490532408892719216
    rotomcore = 1490532913924538481
    snorlax_savings = 1490533390414516425
    hatenna = 1490652070292881428
    as_spawn_ping = 1490877166454440096
    as_rarespawn_ping = 1490877230056738888
    common_snipe = 1490897419062218792
    uncommon_snipe = 1490897542039208127
    rare_snipe = 1490897624482451606
    super_rare_snipe = 1490897729080004628
    legendary_snipe = 1490898999241343167
    mega_snipe = 1490899052395761756
    gigantamax_snipe = 1490899119164756199
    golden_snipe = 1490899263931285525
    paldean_snipe = 1490899362849620121
    exclusive_snipe = 1490981002108076052
    shiny_snipe = 1490982404431544320

# 💦☁────────────────────────────────────────────💦☁
#       SHELLSHUCKLE_EMOJIS
# 💦☁────────────────────────────────────────────💦☁
class SHELLSHUCKLE_EMOJIS:

    lordfry = "<:LordFry:1490453099008102410>"
